name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  BLAST_RPC: ${{ secrets.BLAST_RPC }}
  SEPOLIA_RPC: ${{ secrets.SEPOLIA_RPC }}

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Build project
        run: yarn build

      - name: Run tests
        shell: bash
        run: yarn test:unit

#  integration-tests:
#    name: Run Integration Tests
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Install Foundry
#        uses: foundry-rs/foundry-toolchain@v1
#        with:
#          version: nightly
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.x
#          cache: 'yarn'
#
#      - name: Install dependencies
#        run: yarn --frozen-lockfile --network-concurrency 1
#
#      - name: Build project
#        run: yarn build
#
#      - name: Run tests
#        run: yarn test:integration

  lint:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - run: yarn lint
